### ISSUE TITLE
Can VSN300 detect power consumption from electricity grid ?

### ISSUE THREAD

**Issue by nonth** [alexdelprete/ha-abb-powerone-pvi-sunspec#65]
Can VSN300 detect power consumption from electricity grid I've saw some inverter such as Huawei can do it. If VSN300 can how to setup it with Home Assistant ?

Thanks.

**Comment by alexdelprete** [comment]
Sorry for the late reply. I missed this issue.

> Can VSN300 detect power consumption from electricity grid I've saw some inverter such as Huawei can do it.

VSN300 is only a modbus protocol to aurora protocol wifi gateway. Its purpose is to allow management of the inverter via modbus.

In order to see your consumption data, you need power/energy meters installed. Some inverter kits have these installed, some don't. You have to check if you can add them to your inverter. If not, you can check for external solutions and integrate them in HA, there are many energy management hw solutions. Check HA forums.
