### ISSUE TITLE
Model unknown

### ISSUE THREAD

**Issue by naamah75** [alexdelprete/ha-abb-powerone-pvi-sunspec#66]
I would like to report an unsupported inverter model:

```
(opt_comm_model) Model unknown, report to @alexdelprete on the forum the following data: Manuf.: Power-One - Model: -3N41- - Options: 0xF2 - OptModel: 0xF2 - OptModelInt: 242
(read_inv) Reading data failed! Please check Slave ID: 247
(read_inv) Reading data failed! Please check Reg. Base Address: 0
(read_data) Error: check Slave ID: 247 & Base Address: 0
```

**Comment by alexdelprete** [comment]
The problem is not the unknown model, it's that you are not reading any data, ("reading data failed" in the log).

Check IP, port, Slave ID and Base address. Once you see data for the inverter, if the model # is unknown, then report back and we add it. It's just to have the right model written in the sensor, data must always be read.

**Comment by naamah75** [comment]
your integration is working fine, but this message has been appearing in the logs for some time and therefore I decided to send you the feedback as written.

**Comment by alexdelprete** [comment]
Ok, good to know, I saw those errors in the log I thought you couldn't read data. Sorry about the misunderstanding.

So I will add `OptModelInt: 242` but I need to know the name of the model to associate the appropriate string.

**Comment by naamah75** [comment]
UNO-3.0-TL-OUTD

**Comment by alexdelprete** [comment]
Thanks, added it. When I'll publish a new release you should see the correct model in the sensor and in the device info.
